DROP TABLE IF EXISTS PATIENTS;

CREATE TABLE PATIENTS ( ID INT AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(30) NOT NULL, LAST_NAME VARCHAR(30) NOT NULL, GENDER CHAR(1) NOT NULL, PHONE VARCHAR(10), EMAIL VARCHAR(250) DEFAULT NULL );

DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE  ADDRESS (ID  INT AUTO_INCREMENT PRIMARY KEY, PATIENT_ID INT(10), ADDRESS_LINE1 VARCHAR(200) DEFAULT NULL, ADDRESS_LINE2 VARCHAR(200) DEFAULT NULL, CITY VARCHAR(100) DEFAULT NULL, POSTAL_CODE VARCHAR(100) DEFAULT NULL, COUNTRY_CODE CHAR(2) DEFAULT NULL, STATE VARCHAR(100) DEFAULT NULL, IS_DEFAULT BOOLEAN);

ALTER TABLE ADDRESS ADD FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID);

ALTER TABLE PATIENTS ADD CONSTRAINT PATIENTS_UNIQUE UNIQUE ( ID, EMAIL );